import { Outfit } from "next/font/google";
import { VoiceAssistant } from "@/components/VoiceAssistant";
import "./globals.css";

const font = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${font.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <VoiceAssistant />
      </body>
    </html>
  );
}
